create sequence hibernate_sequence start 1 increment 1;

create table users (
                       id bigint not null generated by default as identity,
                       password varchar not null,
                       username varchar not null unique,
                       primary key (id)
);

create table todos (
                       id bigint not null generated by default as identity,
                       title varchar not null,
                       completed boolean not null,
                       user_id bigint references users(id),
                       primary key (id)
);